### ISSUE TITLE
§3-6-1. リンクのtarget属性(_self,_top_parent)の違いがわかりませんでした。

### ISSUE THREAD

**Issue by toshihirooya** [dip-dev/web-basic#15]
aタグのtarget属性(_self,_top,_parent)の違いがわかりませんでした。実際にtarget属性にそれぞれ指定して動作の違いを見てみましたがsafariでは特に違いがみられませんでした。_blankを指定すると新しいウィンドウでリンク先が開かれるのでわかるのですが...

**Comment by smorikawa** [comment]
ウインドウと書かれているのがよろしくないですね。フレーム（frame）のことです。
フレームを階層構造にしている場合、意味があります。いまどきのサイトでフレーム使っているサイトも見かけなくなりましたが…。
_parent：「現在のウィンドウの親ウィンドウでリンク先を開く」はフレームを階層構造にしていた場合、ひとつ上の階層のフレーム以下でリンク先を開く。
_top：現在のウィンドウの最上位階層のウィンドウでリンク先を開く」はフレームの階層構造をすっ飛ばして、ページ全体でリンク先を開く。

**Comment by mi-shirakawa** [comment]
なんだかんだいってコレがわかりやすい。
http://www.htmq.com/html5/a.shtml

あと、フレームは、コレですね...SEOには不向きということと色んな時代の流れがあっていなくなりました。
http://www.htmq.com/html/frame.shtml

**Comment by a-tomokane** [comment]
説明したのでクローズ！

@mi-shirakawa リンクありがとうございました。

**Comment by a-tomokane** [comment]
フレームで作られたサイト、懐かしいですね。
